Clinic/Clinic/Models/ErrorViewModel.cs
namespace Clinic.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Clinic/Clinic/Controllers/DoctorController.cs
using Clinic.BL;
using Clinic.DAL;
using Microsoft.AspNetCore.Mvc;


namespace Clinic.Controllers
{
    public class DoctorController : Controller
    {
        private IDoctorManager _doctorManager;

        public DoctorController(IDoctorManager doctorManager)
        {
            _doctorManager = doctorManager;
        }
        public ActionResult<IEnumerable<Doctor>> Index()
        {
            IEnumerable<Doctor> objDoctortList = _doctorManager.GetAllDoctors();
            return View(objDoctortList);
           
        }
        public IActionResult DoctorAppointment(int id)
        {
            var _doctor = _doctorManager.GetDoctorById(id);
            var appointments = _doctorManager.GetAllDoctorAppointmentDay(id);
            // Pass the appointments and doctor to the view
            ViewBag.Doctor = _doctor;
            return View(appointments);

        }
    }
}

Clinic/Clinic/Controllers/HomeController.cs
using Clinic.BL;
using Clinic.DAL;
using Clinic.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Clinic.Controllers
{
    public class HomeController : Controller
    {
        private IAppointmentManager _appointmentManager;
        private IDoctorManager _doctorManager;

        public HomeController(IAppointmentManager appointmentManager,IDoctorManager doctorManager)
        {
            _appointmentManager = appointmentManager;
            _doctorManager = doctorManager;
        }

        public IActionResult Index()
        {
            var appointments = _appointmentManager.GetAllAppointmentsWithPatientAndDoctor();
            return View(appointments);
        }
        public IActionResult Create()
        {
            var doctors = _doctorManager.GetAllDoctors().ToList();
            ViewBag.Doctors=doctors;
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Create(CreateAppointmentViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result =await _appointmentManager.AddAppointmentAndPatient(model);
                if (result == false)
                {
                    ModelState.AddModelError("", "An appointment already exists at this date and time.");
                    return View(model);
                }if(result == true)
                {
                    return RedirectToAction("Index");
                }
            }

            // If model is not valid return the view with the validation errors
            return View(model);
        }
        public IActionResult Privacy()
        {
            return View();
        }

    }
}

Clinic/Clinic/Views/Doctor/DoctorAppointment.cshtml
@using Clinic.DAL
@model List<Appointment>
@{
    ViewData["Title"] = "DoctorAppointment";
}
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Dr : @ViewBag.Doctor.Name's Appointments</h2>
        </div>
    </div>
    <br /><br />

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Patient Name
                </th>

                <th>
                    Appointment Date
                </th>
                <th>
                    Appointment Time
                </th>
               
            </tr>
        </thead>
        <tbody>
            @foreach (var appointment in Model)
            {
                <tr>
                    <td width="30%">
                        @appointment.Patient.Name
                    </td>
                    <td width="50%">
                        @appointment.Date.ToShortDateString()
                    </td>
                    <td width="30%">
                        @appointment.Time.ToShortTimeString()
                    </td>
                   
                </tr>
            }
        </tbody>

    </table>
</div>
<a asp-controller="Doctor" asp-action="Index" class="btn btn-primary">
    <i class="bi bi-plus-circle"></i> Back
</a>

Clinic/Clinic/Views/Doctor/Index.cshtml
@using Clinic.DAL
@model IEnumerable<Doctor>
@{
    ViewData["Title"] = "Index";
}
<div class="p-3">
    @foreach (var obj in Model)
    {
        <div class="card mb-2">
            <div class="card-body d-flex justify-content-between">
                <div>
                    <h4 class="card-title fw-bold">Doctor Name<span class="fw-light fs-5">: @obj.Name</span> </h4>
                    <h4 class="card-text fw-bold">Doctor Specialty <span class="fw-light fs-5">: @obj.Specialty</span></h4>
                </div>
                <div>
                    <a asp-controller="Doctor" asp-action="DoctorAppointment" asp-route-id="@obj.DoctorId" class="btn btn-primary">View Appointments</a>
                </div>
            </div>
        </div>
    }
</div>
<a asp-controller="Home" asp-action="Index" class="btn btn-primary">
    <i class="bi bi-plus-circle"></i> Back
</a>

Clinic/Clinic/Views/Home/Create.cshtml
@using Clinic.DAL
@model CreateAppointmentViewModel

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-warning mt-3">
        <p>
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <h6>@error.ErrorMessage</h6>
            }
        </p>
     </div>
}
<form asp-action="Create" method="post" class="p-4">
    <div class="form-group py-2">
        <label asp-for="DoctorName" class="control-label"></label>
        <select asp-for="DoctorName">
            <option value="">-- Select Doctor --</option>
            @foreach (var doctor in ViewBag.Doctors)
            {
                <option value="@doctor.Name">@doctor.Name</option>

            }
            
            <span asp-validation-for="DoctorName" class="text-danger"></span>
        </select>
    </div>
    <div class="form-group py-2">
        <label asp-for="PatientName" class="control-label"></label>
        <input asp-for="PatientName" class="form-control">
        <span asp-validation-for="PatientName" class="text-danger"></span>
    </div>
    <div class="form-group py-2">
        <label asp-for="PatientBirthDate" class="control-label"></label>
        <input asp-for="PatientBirthDate" class="form-control" />
        <span asp-validation-for="PatientBirthDate" class="text-danger"></span>
    </div>
    <div class="form-group py-2">
        <label asp-for="PatientPhone" class="control-label"></label>
        <input asp-for="PatientPhone" class="form-control" />
        <span asp-validation-for="PatientPhone" class="text-danger"></span>
    </div>
    <div class="form-group py-2">
        <label asp-for="AppointmentDate" class="control-label"></label>
        <input asp-for="AppointmentDate" class="form-control" />
        <span asp-validation-for="AppointmentDate" class="text-danger"></span>
    </div>
    <div class="form-group py-2">
        <label asp-for="AppointmentTime" class="control-label"></label>
        <input asp-for="AppointmentTime" class="form-control" />
        <span asp-validation-for="AppointmentTime" class="text-danger"></span>
    </div>
    <div class="form-group pt-3">
        <input type="submit" value="Save" class="btn btn-primary" />
        <a asp-controller="Home" asp-action="Index" class="btn btn-light">
            <i class="bi bi-plus-circle"></i> Back
        </a>
    </div>
</form>

Clinic/Clinic/Views/Home/Index.cshtml
@using Clinic.DAL
@model List<AppointmentViewModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Appointment List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Home" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Appointment
            </a>
        </div>
    </div>
    <br /><br />

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Patient Name
                </th>
                <th>
                    Doctor
                </th>
                <th>
                    Appointment Date
                </th>
                <th>
                    Appointment Time
                </th>
                @*<th></th>*@
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="30%">
                        @obj.PatientName
                    </td>
                    <td width="30%">
                        @obj.DoctorName
                    </td>
                    <td width="50%">
                        @obj.Date.ToShortDateString()
                    </td>
                    <td width="30%">
                        @obj.Time.TimeOfDay
                    </td>
                   
                    @*<td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Category" asp-action="Edit" asp-route-id="@obj.Id"
                           class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                            <a asp-controller="Category" asp-action="Delete" asp-route-id="@obj.Id"
                           class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
                        </div>
                    </td>*@
                </tr>
            }
        </tbody>

    </table>
</div>

Clinic/Clinic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Clinic</title>
    <link rel="stylesheet" href="~/css/bootwatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Clinic.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Clinic</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Doctor" asp-action="Index">Doctors</a>
                        </li>
                       
                    </ul>
                   </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2023 - Clinic - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>